# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2023_09_24_013323) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "agencies", force: :cascade do |t|
    t.bigint "organization_id"
    t.integer "agency_license_category"
    t.string "license_number"
    t.datetime "license_expired_at"
    t.string "director_name"
    t.string "director_ic_number"
    t.string "pic_name"
    t.string "pic_ic_number"
    t.string "pic_phone"
    t.string "address1"
    t.string "address2"
    t.string "address3"
    t.string "address4"
    t.integer "country_id"
    t.integer "state_id"
    t.integer "town_id"
    t.string "postcode"
    t.string "phone"
    t.string "email"
    t.boolean "personal_data_consent"
    t.string "status"
    t.string "registration_comment"
    t.datetime "registration_approved_at"
    t.string "registration_approval_by"
    t.datetime "activated_at"
    t.string "approval_status"
    t.string "approval_remark"
    t.integer "bank_payment_id"
    t.integer "bank_id"
    t.string "bank_account_number"
    t.datetime "expired_at"
    t.boolean "renewal_order_created"
    t.boolean "problematic"
    t.boolean "document_verified"
    t.boolean "agreement_accepted"
    t.boolean "sop_acknowledge"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["organization_id"], name: "index_agencies_on_organization_id"
  end

  create_table "approval_requests", force: :cascade do |t|
    t.integer "request_user_id"
    t.integer "respond_user_id"
    t.integer "state"
    t.datetime "requested_at"
    t.datetime "cancelled_at"
    t.datetime "approved_at"
    t.datetime "rejected_at"
    t.datetime "executed_at"
    t.boolean "is_draft"
    t.string "category"
    t.string "approval_decision"
    t.integer "approval_user_id"
    t.datetime "approval_at"
    t.string "approval2_decision"
    t.integer "approval2_user_id"
    t.datetime "approval2_at"
    t.json "additional_information"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "conditions", force: :cascade do |t|
    t.string "code"
    t.text "description"
    t.string "exam_type"
    t.string "field_type"
    t.string "category"
    t.bigint "created_by"
    t.bigint "updated_by"
    t.datetime "deleted_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["created_at"], name: "index_conditions_on_created_at"
    t.index ["deleted_at"], name: "index_conditions_on_deleted_at"
    t.index ["updated_at"], name: "index_conditions_on_updated_at"
  end

  create_table "countries", force: :cascade do |t|
    t.string "old_code"
    t.string "code"
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "created_by"
    t.string "updated_by"
  end

  create_table "doctor_examination_details", force: :cascade do |t|
    t.bigint "transaction_id"
    t.integer "condition_id"
    t.bigint "doctor_examination_id"
    t.date "date_value"
    t.string "text_value"
    t.bigint "created_by"
    t.bigint "updated_by"
    t.datetime "deleted_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "history"
    t.index ["created_at"], name: "index_doctor_examination_details_on_created_at"
    t.index ["deleted_at"], name: "index_doctor_examination_details_on_deleted_at"
    t.index ["updated_at"], name: "index_doctor_examination_details_on_updated_at"
  end

  create_table "doctor_examinations", force: :cascade do |t|
    t.bigint "transaction_id"
    t.bigint "doctor_id"
    t.decimal "physical_height"
    t.decimal "physical_weight"
    t.integer "physical_pulse"
    t.integer "physical_blood_pressure_systolic"
    t.integer "physical_blood_pressure_diastolic"
    t.date "physical_last_menstrual_period_date"
    t.string "result"
    t.string "suitability"
    t.datetime "transmitted_at"
    t.bigint "created_by"
    t.bigint "updated_by"
    t.datetime "deleted_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["created_at"], name: "index_doctor_examinations_on_created_at"
    t.index ["deleted_at"], name: "index_doctor_examinations_on_deleted_at"
    t.index ["updated_at"], name: "index_doctor_examinations_on_updated_at"
  end

  create_table "doctors", force: :cascade do |t|
    t.string "code"
    t.string "name"
    t.string "company_name"
    t.integer "title_id"
    t.string "clinic_name"
    t.string "icno"
    t.string "address1"
    t.string "address2"
    t.string "address3"
    t.string "address4"
    t.integer "country_id"
    t.integer "state_id"
    t.integer "town_id"
    t.string "postcode"
    t.string "phone"
    t.string "fax"
    t.string "mobile"
    t.string "email"
    t.string "email_payment"
    t.string "qualification"
    t.integer "apc_year"
    t.string "apc_number"
    t.datetime "renewal_agreement_date"
    t.integer "district_health_office_id"
    t.boolean "has_xray"
    t.integer "fp_device"
    t.integer "quota"
    t.integer "quota_used"
    t.integer "quota_modifier"
    t.boolean "solo_clinic"
    t.boolean "group_clinic"
    t.integer "xray_facility_id"
    t.integer "laboratory_id"
    t.text "comment"
    t.string "pairing_options"
    t.integer "service_provider_group_id"
    t.integer "male_rate"
    t.integer "female_rate"
    t.integer "bank_id"
    t.string "bank_account_number"
    t.integer "bank_payment_id"
    t.string "status"
    t.string "status_reason"
    t.datetime "registration_approved_at"
    t.datetime "activated_at"
    t.string "approval_status"
    t.text "approval_remark"
    t.string "created_by"
    t.string "updated_by"
    t.integer "payment_method_id"
    t.string "business_registration_number"
    t.text "status_comment"
    t.boolean "has_doctor_association"
    t.string "name_of_association"
    t.boolean "has_selected_re_medical"
    t.string "gender"
    t.integer "nationality_id"
    t.integer "race_id"
    t.text "associations"
    t.boolean "paid_biometric_device"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "employers", force: :cascade do |t|
    t.string "code"
    t.bigint "employer_type_id"
    t.string "name"
    t.string "business_registration_number"
    t.string "ic_passport_number"
    t.string "address1"
    t.string "address2"
    t.string "address3"
    t.string "address4"
    t.bigint "country_id"
    t.bigint "state_id"
    t.bigint "town_id"
    t.string "postcode"
    t.string "phone"
    t.string "fax"
    t.string "email"
    t.string "pic_name"
    t.string "pic_phone"
    t.boolean "personal_data_consent"
    t.string "status"
    t.boolean "bad_payment"
    t.boolean "blacklisted"
    t.datetime "blacklisted_at"
    t.text "comment"
    t.text "registration_comment"
    t.datetime "registration_approved_at"
    t.bigint "registration_approval_by"
    t.datetime "activated_at"
    t.string "approval_status"
    t.string "approval_remark"
    t.bigint "created_by"
    t.bigint "updated_by"
    t.bigint "bank_id"
    t.string "bank_account_number"
    t.bigint "organization_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "foreign_workers", force: :cascade do |t|
    t.string "code"
    t.string "name"
    t.string "passport_number"
    t.string "gender"
    t.datetime "gender_amended_at"
    t.date "date_of_birth"
    t.bigint "employer_id"
    t.bigint "employer_supplement_id"
    t.bigint "country_id"
    t.bigint "job_type_id"
    t.date "arrival_date"
    t.string "plks_number"
    t.boolean "pati"
    t.text "amendment_reason_comment"
    t.datetime "employer_amended_at"
    t.datetime "amended_at"
    t.bigint "amended_by"
    t.boolean "blocked"
    t.bigint "block_reason_id"
    t.text "block_comment"
    t.bigint "unblock_reason_id"
    t.text "unblock_comment"
    t.datetime "blocked_at"
    t.bigint "blocked_by"
    t.string "afis_id"
    t.string "approval_status"
    t.string "approval_remark"
    t.bigint "created_by"
    t.bigint "updated_by"
    t.json "amendment_reasons"
    t.string "maid_online"
    t.string "monitoring"
    t.bigint "monitor_reason_id"
    t.text "monitor_comment"
    t.text "unmonitor_comment"
    t.bigint "organization_id"
    t.bigint "latest_transaction_id"
    t.integer "reg_ind"
    t.integer "med_ind_count"
    t.string "status"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "fw_change_employers", force: :cascade do |t|
    t.integer "foreign_worker_id"
    t.integer "customerable_id"
    t.string "customerable_type"
    t.integer "old_employer_id"
    t.integer "new_employer_id"
    t.string "fw_name"
    t.string "fw_passport_number"
    t.integer "fw_country_id"
    t.string "fw_gender"
    t.date "fw_date_of_birth"
    t.integer "requested_by"
    t.datetime "requested_at"
    t.integer "approval_by"
    t.datetime "approval_at"
    t.string "decision"
    t.string "status"
    t.string "approval_comment"
    t.string "comment"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "created_by"
    t.integer "updated_by"
    t.integer "assigned_to"
  end

  create_table "insurance_purchases", force: :cascade do |t|
    t.integer "order_id"
    t.integer "order_item_id"
    t.date "start_date"
    t.date "end_date"
    t.string "product_purchased"
    t.integer "batch_id"
    t.integer "reg_id"
    t.integer "employer_id"
    t.string "fw_name"
    t.integer "insurance_provider"
    t.string "status"
    t.string "emp_code"
    t.string "emp_name"
    t.integer "foreign_worker_id"
    t.string "fw_code"
    t.string "fw_gender"
    t.date "fw_date_of_birth"
    t.string "fw_passport_number"
    t.integer "fw_country_id"
    t.integer "fw_job_type_id"
    t.boolean "is_collection"
    t.integer "gross_premium"
    t.integer "stamp_duty"
    t.integer "sst"
    t.integer "adminfees"
    t.integer "adminfees_sst"
    t.integer "total_premium"
    t.integer "insurance_service_provider_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "job_types", force: :cascade do |t|
    t.string "name"
    t.string "created_by"
    t.string "updated_by"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "laboratories", force: :cascade do |t|
    t.string "code"
    t.string "name"
    t.string "company_name"
    t.string "business_registration_number"
    t.string "address1"
    t.string "address2"
    t.string "address3"
    t.string "address4"
    t.integer "country_id"
    t.integer "state_id"
    t.integer "town_id"
    t.string "postcode"
    t.string "phone"
    t.string "fax"
    t.string "email"
    t.string "email_payment"
    t.string "pic_name"
    t.string "pic_phone"
    t.string "qualification"
    t.string "pathologist_name"
    t.string "nsr_number"
    t.integer "laboratory_type_id"
    t.date "renewal_agreement_date"
    t.integer "district_health_office_id"
    t.string "samm_number"
    t.string "license"
    t.integer "license_year"
    t.string "web_service"
    t.string "web_service_passphrase"
    t.text "comment"
    t.integer "service_provider_group_id"
    t.integer "male_rate"
    t.integer "female_rate"
    t.integer "bank_id"
    t.string "bank_account_number"
    t.string "bank_payment_id"
    t.string "status"
    t.string "status_reason"
    t.datetime "registration_approved_at"
    t.datetime "activated_at"
    t.string "approval_status"
    t.text "approval_remark"
    t.string "created_by"
    t.string "updated_by"
    t.integer "payment_method_id"
    t.date "samm_accredited_since"
    t.date "samm_expiry_date"
    t.text "status_comment"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "medical_appeals", force: :cascade do |t|
    t.integer "transaction_id"
    t.string "registered_by_type"
    t.integer "created_by"
    t.integer "officer_in_charge_id"
    t.integer "doctor_id"
    t.integer "laboratory_id"
    t.integer "xray_facility_id"
    t.string "doctor_reason"
    t.string "appeal_reason"
    t.string "status"
    t.string "result"
    t.datetime "officer_assigned_at"
    t.integer "radiologist_id"
    t.string "pcr_result"
    t.string "xray_result"
    t.datetime "xray_selected_at"
    t.datetime "doctor_done_at"
    t.datetime "laboratory_done_at"
    t.datetime "xray_facility_done_at"
    t.datetime "radiologist_done_at"
    t.integer "updated_by"
    t.datetime "deleted_at"
    t.datetime "completed_at"
    t.boolean "is_amendment"
    t.boolean "latest_appeal"
    t.datetime "employer_consented_at"
    t.boolean "doctor_document_uploaded"
    t.boolean "laboratory_document_uploaded"
    t.boolean "is_moh"
    t.boolean "employer_document_uploaded"
    t.boolean "is_specialist"
    t.datetime "employer_document_uploaded_date"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "medical_examination_details", force: :cascade do |t|
    t.bigint "transaction_id"
    t.integer "condition_id"
    t.bigint "medical_examination_id"
    t.date "date_value"
    t.string "text_value"
    t.bigint "created_by"
    t.bigint "updated_by"
    t.datetime "deleted_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "history"
    t.index ["created_at"], name: "index_medical_examination_details_on_created_at"
    t.index ["deleted_at"], name: "index_medical_examination_details_on_deleted_at"
    t.index ["updated_at"], name: "index_medical_examination_details_on_updated_at"
  end

  create_table "medical_examinations", force: :cascade do |t|
    t.bigint "transaction_id"
    t.decimal "physical_height"
    t.decimal "physical_weight"
    t.integer "physical_pulse"
    t.integer "physical_blood_pressure_systolic"
    t.integer "physical_blood_pressure_diastolic"
    t.date "physical_last_menstrual_period_date"
    t.string "result"
    t.string "suitability"
    t.datetime "transmitted_at"
    t.bigint "created_by"
    t.bigint "updated_by"
    t.datetime "deleted_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["created_at"], name: "index_medical_examinations_on_created_at"
    t.index ["deleted_at"], name: "index_medical_examinations_on_deleted_at"
    t.index ["updated_at"], name: "index_medical_examinations_on_updated_at"
  end

  create_table "myimms_transactions", force: :cascade do |t|
    t.integer "transaction_id"
    t.integer "status"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "created_by"
    t.integer "updated_by"
  end

  create_table "orders", force: :cascade do |t|
    t.string "code"
    t.integer "customerable_id"
    t.string "customerable_type"
    t.integer "payment_method_id"
    t.string "category"
    t.time "date"
    t.decimal "amount"
    t.string "status"
    t.text "comment"
    t.text "additional_information"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "created_by"
    t.integer "updated_by"
    t.integer "organization_id"
    t.time "paid_at"
    t.integer "master_reference_id"
    t.integer "reference_id"
    t.boolean "personal_data_consent"
    t.integer "insurance_service_provider_id"
  end

  create_table "organizations", force: :cascade do |t|
    t.integer "parent_id"
    t.string "code"
    t.string "name"
    t.string "address1"
    t.string "address2"
    t.string "address3"
    t.string "address4"
    t.integer "state_id"
    t.integer "town_id"
    t.string "postcode"
    t.string "phone"
    t.string "fax"
    t.string "email"
    t.string "org_type"
    t.string "bank_code"
    t.string "bank_co"
    t.string "bank_acctno"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "created_by"
    t.integer "updated_by"
    t.integer "zone_id"
    t.string "status"
  end

  create_table "pcr_pools", id: :serial, force: :cascade do |t|
    t.bigint "transaction_id"
    t.string "case_type"
    t.string "status"
    t.string "source"
    t.string "sourceable_type"
    t.bigint "sourceable_id"
    t.datetime "picked_up_at"
    t.bigint "created_by_id"
    t.bigint "updated_by_id"
    t.bigint "picked_up_by_id"
    t.boolean "is_legacy", default: false, null: false
    t.string "trans_id"
    t.bigint "legacy_id"
    t.bigint "medical_appeal_id"
    t.bigint "xray_retake_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "pcr_reviews", force: :cascade do |t|
    t.bigint "transaction_id"
    t.string "case_type"
    t.text "comment"
    t.string "status"
    t.string "result"
    t.datetime "transmitted_at"
    t.bigint "created_by_id"
    t.bigint "updated_by_id"
    t.bigint "pcr_id"
    t.string "poolable_type"
    t.bigint "poolable_id"
    t.boolean "is_legacy"
    t.string "trans_id"
    t.bigint "legacy_id"
    t.bigint "medical_appeal_id"
    t.string "belong"
    t.text "belong_comment"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "states", force: :cascade do |t|
    t.string "code"
    t.string "name"
    t.string "long_name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "created_by"
    t.integer "updated_by"
  end

  create_table "towns", force: :cascade do |t|
    t.string "code"
    t.string "name"
    t.bigint "state_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "created_by"
    t.integer "updated_by"
    t.index ["state_id"], name: "index_towns_on_state_id"
  end

  create_table "transactions", force: :cascade do |t|
    t.string "code"
    t.integer "order_item_id"
    t.integer "foreign_worker_id"
    t.integer "employer_id"
    t.integer "doctor_id"
    t.integer "laboratory_id"
    t.integer "xray_facility_id"
    t.integer "radiologist_id"
    t.datetime "transaction_date"
    t.datetime "medical_examination_date"
    t.datetime "doctor_transmit_date"
    t.datetime "laboratory_transmit_date"
    t.datetime "xray_transmit_date"
    t.datetime "expired_at"
    t.datetime "extended_at"
    t.datetime "certification_date"
    t.string "status"
    t.text "comment"
    t.boolean "worker_matched"
    t.boolean "worker_consented"
    t.boolean "worker_identity_confirmed"
    t.boolean "xray_worker_identity_confirmed"
    t.string "xray_film_type"
    t.string "xray_reporter_type"
    t.string "medical_tcupi"
    t.boolean "medical_status"
    t.string "medical_result"
    t.boolean "xray_status"
    t.string "xray_result"
    t.integer "xray_pending_review_id"
    t.integer "final_result"
    t.integer "approval_status"
    t.string "approval_remark"
    t.boolean "doctor_fp_result"
    t.boolean "xray_fp_result"
    t.integer "doctor_fp"
    t.integer "xray_fp"
    t.boolean "physical_exam_not_done"
    t.integer "not_done_officer_id"
    t.datetime "not_done_set_at"
    t.datetime "tcupi_date"
    t.boolean "ignore_expiry"
    t.string "fw_code"
    t.string "fw_name"
    t.string "fw_gender"
    t.date "fw_date_of_birth"
    t.string "fw_passport_number"
    t.integer "fw_country_id"
    t.string "fw_maid_online"
    t.string "fw_plks_number"
    t.integer "organization_id"
    t.integer "fw_job_type_id"
    t.boolean "is_special_renewal"
    t.datetime "doctor_fp_result_date"
    t.datetime "xray_fp_result_date"
    t.integer "digital_xray_provider_id"
    t.integer "doctor_bypass_fingerprint_reason_id"
    t.integer "xray_bypass_fingerprint_reason_id"
    t.datetime "ignore_merts_expiry_at"
    t.datetime "final_result_date"
    t.boolean "unsuitable_slip_download"
    t.integer "pcr_review_id"
    t.integer "xray_retake_id"
    t.datetime "special_renewal_rejected_at"
    t.integer "registration_type"
    t.integer "xray_review_id"
    t.boolean "reg_ind"
    t.boolean "medical_pr_source"
    t.integer "med_ind_count"
    t.integer "xray_pending_decision_id"
    t.datetime "doctor_bypass_fingerprint_date"
    t.datetime "xray_bypass_fingerprint_date"
    t.datetime "medical_quarantine_release_date"
    t.datetime "xray_quarantine_release_date"
    t.boolean "communicable_diseases"
    t.boolean "ignore_reprint_rule"
    t.boolean "unsuitable_slip_downloaded"
    t.boolean "fw_pati"
    t.boolean "ignore_cancellation_rule"
    t.boolean "is_imm_insert"
    t.boolean "is_imm_blocked"
    t.boolean "is_sp_transmit_blocked"
    t.boolean "is_blood_group_benchmark"
    t.boolean "ignore_renewal_rule"
    t.integer "agency_id"
    t.boolean "worker_image_confirmed"
    t.boolean "xray_worker_image_confirmed"
    t.datetime "transmission_expired_at"
    t.datetime "condition_amended_at"
    t.boolean "ignore_special_renewal_rule"
    t.boolean "medical_report_letter_download"
    t.boolean "is_next_transaction_re_medical"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "users", force: :cascade do |t|
    t.string "email"
    t.string "encrypted_password"
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer "sign_in_count"
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.inet "current_sign_in_ip"
    t.inet "last_sign_in_ip"
    t.string "confirmation_token"
    t.datetime "confirmed_at"
    t.datetime "confirmation_sent_at"
    t.string "unconfirmed_email"
    t.integer "failed_attempts"
    t.string "unlock_token"
    t.datetime "locked_at"
    t.string "code"
    t.string "username"
    t.string "name"
    t.string "status"
    t.string "activation_token"
    t.string "userable_type"
    t.bigint "userable_id"
    t.bigint "employer_supplement_id"
    t.bigint "title_id"
    t.bigint "created_by"
    t.bigint "updated_by"
    t.datetime "deleted_at"
    t.datetime "password_changed_at"
    t.string "unique_session_id", limit: 20
    t.bigint "role_id"
    t.string "designation"
    t.text "comment"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "xqcc_pools", force: :cascade do |t|
    t.integer "transaction_id"
    t.string "case_type"
    t.string "status"
    t.string "source"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.time "picked_up_at"
    t.integer "created_by"
    t.integer "updated_by"
    t.integer "picked_up_by"
    t.string "sourceable_type"
    t.integer "sourceable_id"
    t.boolean "is_legacy"
    t.integer "trans_id"
    t.integer "legacy_id"
    t.integer "reserved_by"
  end

  create_table "xray_facilities", force: :cascade do |t|
    t.string "code"
    t.string "name"
    t.string "company_name"
    t.integer "title_id"
    t.string "address1"
    t.string "address2"
    t.string "address3"
    t.string "address4"
    t.integer "country_id"
    t.integer "state_id"
    t.integer "town_id"
    t.string "postcode"
    t.string "phone"
    t.string "fax"
    t.string "email"
    t.string "email_payment"
    t.string "icno"
    t.string "mobile"
    t.string "qualification"
    t.integer "district_health_office_id"
    t.string "xray_license_number"
    t.string "xray_file_number"
    t.boolean "xray_fac_flag"
    t.string "xray_license_tujuan"
    t.date "xray_license_expiry_date"
    t.boolean "radiologist_operated"
    t.string "radiologist_name"
    t.integer "apc_year"
    t.string "apc_number"
    t.string "film_type"
    t.date "renewal_agreement_date"
    t.boolean "fp_device"
    t.text "comment"
    t.integer "service_provider_group_id"
    t.decimal "male_rate", precision: 10, scale: 2
    t.decimal "female_rate", precision: 10, scale: 2
    t.integer "bank_id"
    t.string "bank_account_number"
    t.string "bank_payment_id"
    t.string "status"
    t.text "status_reason"
    t.datetime "registration_approved_at"
    t.datetime "activated_at"
    t.integer "approval_status"
    t.text "approval_remark"
    t.integer "created_by"
    t.integer "updated_by"
    t.integer "payment_method_id"
    t.string "license_holder_name"
    t.string "business_registration_number"
    t.text "status_comment"
    t.boolean "moh_license_status"
    t.boolean "has_doctor_association"
    t.string "name_of_association"
    t.string "gender"
    t.boolean "has_selected_re_medical"
    t.integer "nationality_id"
    t.integer "race_id"
    t.text "associations"
    t.integer "xray_license_purposes_id"
    t.integer "digital_xray_provider_id"
    t.boolean "paid_biometric_device"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "xray_pending_decisions", force: :cascade do |t|
    t.bigint "transaction_id"
    t.text "comment"
    t.string "status"
    t.string "decision"
    t.string "sourceable_type"
    t.bigint "sourceable_id"
    t.datetime "transmitted_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "created_by"
    t.bigint "updated_by"
    t.bigint "reviewed_by"
    t.string "condition_hiv"
    t.string "condition_tuberculosis"
    t.string "condition_malaria"
    t.string "condition_leprosy"
    t.string "condition_std"
    t.string "condition_hepatitis"
    t.string "condition_cancer"
    t.string "condition_epilepsy"
    t.string "condition_psychiatric_disorder"
    t.string "condition_other"
    t.string "condition_hypertension"
    t.string "condition_heart_diseases"
    t.string "condition_bronchial_asthma"
    t.string "condition_diabetes_mellitus"
    t.string "condition_peptic_ulcer"
    t.string "condition_kidney_diseases"
    t.string "condition_urine_for_pregnant"
    t.string "condition_urine_for_opiates"
    t.string "condition_urine_for_cannabis"
    t.text "certification_comment"
    t.boolean "is_legacy"
    t.string "trans_id"
    t.bigint "legacy_id"
    t.bigint "pcr_id"
    t.bigint "approval_by"
    t.string "approval_decision"
    t.text "approval_comment"
    t.datetime "reviewed_at"
  end

  create_table "xray_pending_reviews", force: :cascade do |t|
    t.bigint "transaction_id"
    t.string "quarantine_type"
    t.text "quarantine_reason"
    t.string "source"
    t.text "comment"
    t.string "status"
    t.string "decision"
    t.datetime "transmitted_at"
    t.bigint "created_by"
    t.bigint "updated_by"
    t.bigint "reviewed_by"
    t.string "is_audit_comparison"
    t.boolean "is_legacy"
    t.string "trans_id"
    t.bigint "legacy_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["transaction_id"], name: "index_xray_pending_reviews_on_transaction_id"
  end

  create_table "xray_reviews", force: :cascade do |t|
    t.integer "transaction_id"
    t.integer "batch_id"
    t.string "case_type"
    t.string "status"
    t.string "result"
    t.time "transmitted_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "created_by"
    t.integer "updated_by"
    t.integer "radiographer_id"
    t.string "poolable_type"
    t.integer "poolable_id"
    t.boolean "is_legacy"
    t.string "trans_id"
    t.integer "legacy_id"
    t.string "is_iqa", limit: 1
  end

  add_foreign_key "agencies", "organizations"
  add_foreign_key "towns", "states"
  add_foreign_key "xray_pending_reviews", "transactions"
end
