class CreateTransactions < ActiveRecord::Migration[5.2]
  def change
    create_table :transactions do |t|
      t.string :code
      t.integer :order_item_id
      t.integer :foreign_worker_id
      t.integer :employer_id
      t.integer :doctor_id
      t.integer :laboratory_id
      t.integer :xray_facility_id
      t.integer :radiologist_id
      t.timestamp :transaction_date
      t.timestamp :medical_examination_date
      t.timestamp :doctor_transmit_date
      t.timestamp :laboratory_transmit_date
      t.timestamp :xray_transmit_date
      t.timestamp :expired_at
      t.timestamp :extended_at
      t.timestamp :certification_date
      t.string :status
      t.text :comment
      t.boolean :worker_matched
      t.boolean :worker_consented
      t.boolean :worker_identity_confirmed
      t.boolean :xray_worker_identity_confirmed
      t.string :xray_film_type
      t.string :xray_reporter_type
      t.string :medical_tcupi
      t.boolean :medical_status
      t.string :medical_result
      t.boolean :xray_status
      t.string :xray_result
      t.integer :xray_pending_review_id
      t.integer :final_result
      t.integer :approval_status
      t.string :approval_remark
      t.boolean :doctor_fp_result
      t.boolean :xray_fp_result
      t.integer :doctor_fp
      t.integer :xray_fp
      t.boolean :physical_exam_not_done
      t.integer :not_done_officer_id
      t.timestamp :not_done_set_at
      t.timestamp :tcupi_date
      t.boolean :ignore_expiry
      t.string :fw_code
      t.string :fw_name
      t.string :fw_gender
      t.date :fw_date_of_birth
      t.string :fw_passport_number
      t.integer :fw_country_id
      t.string :fw_maid_online
      t.string :fw_plks_number
      t.integer :organization_id
      t.integer :fw_job_type_id
      t.boolean :is_special_renewal
      t.timestamp :doctor_fp_result_date
      t.timestamp :xray_fp_result_date
      t.integer :digital_xray_provider_id
      t.integer :doctor_bypass_fingerprint_reason_id
      t.integer :xray_bypass_fingerprint_reason_id
      t.timestamp :ignore_merts_expiry_at
      t.timestamp :final_result_date
      t.boolean :unsuitable_slip_download
      t.integer :pcr_review_id
      t.integer :xray_retake_id
      t.timestamp :special_renewal_rejected_at
      t.integer :registration_type
      t.integer :xray_review_id
      t.boolean :reg_ind
      t.boolean :medical_pr_source
      t.integer :med_ind_count
      t.integer :xray_pending_decision_id
      t.timestamp :doctor_bypass_fingerprint_date
      t.timestamp :xray_bypass_fingerprint_date
      t.timestamp :medical_quarantine_release_date
      t.timestamp :xray_quarantine_release_date
      t.boolean :communicable_diseases
      t.boolean :ignore_reprint_rule
      t.boolean :unsuitable_slip_downloaded
      t.boolean :fw_pati
      t.boolean :ignore_cancellation_rule
      t.boolean :is_imm_insert
      t.boolean :is_imm_blocked
      t.boolean :is_sp_transmit_blocked
      t.boolean :is_blood_group_benchmark
      t.boolean :ignore_renewal_rule
      t.integer :agency_id
      t.boolean :worker_image_confirmed
      t.boolean :xray_worker_image_confirmed
      t.timestamp :transmission_expired_at
      t.timestamp :condition_amended_at
      t.boolean :ignore_special_renewal_rule
      t.boolean :medical_report_letter_download
      t.boolean :is_next_transaction_re_medical

      t.timestamps
    end
  end
end
